[programs.localnet]
myepicproject = "AqYeE39uDeQz8yCSMswbJrqzbd6KXVfiZPWsyoKWPVbj"

[programs.devnet]
myepicproject = "AqYeE39uDeQz8yCSMswbJrqzbd6KXVfiZPWsyoKWPVbj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dave/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
